# HTTP Server
[server]
	Address     = ":80"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:asdfasdf@tcp(192.168.0.166:3306)/nest_label"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true

# 交叉编译
[compiler]
    name = "nest-label"
    version = "20.09.26"
    arch = "amd64"
    system = "linux,darwin"
    output = ""
    path = "./bin"
    extra = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
    [compiler.VarMap]
        author = "zhushao"
        email = "zhushao@nestciao.com"